lovefile:
	@rm -rf build/lovefile
	@mkdir -p build/lovefile

	@cd src/love; zip -r -9 ../../build/lovefile/clothing-hanger-clicker.love .

	@mkdir -p build/release
	@rm -f build/release/clothing-hanger-clicker-lovefile.zip
	@cd build/lovefile; zip -9 -r ../release/clothing-hanger-clicker-lovefile.zip .

win64: lovefile
	@rm -rf build/win64
	@mkdir -p build/win64

	@cp resources/win64/love/OpenAL32.dll build/win64
	@cp resources/win64/love/SDL2.dll build/win64
	@cp resources/win64/love/license.txt build/win64
	@cp resources/win64/love/lua51.dll build/win64
	@cp resources/win64/love/mpg123.dll build/win64
	@cp resources/win64/love/love.dll build/win64
	@cp resources/win64/love/msvcp120.dll build/win64
	@cp resources/win64/love/msvcr120.dll build/win64

	@cat resources/win64/love/love.exe build/lovefile/clothing-hanger-clicker.love > build/win64/clothing-hanger-clicker.exe

	@mkdir -p build/release
	@rm -f build/release/clothing-hanger-clicker-win64.zip
	@cd build/win64; zip -9 -r ../release/clothing-hanger-clicker-win64.zip .

win32: lovefile
	@rm -rf build/win32
	@mkdir -p build/win32

	@cp resources/win32/love/OpenAL32.dll build/win32
	@cp resources/win32/love/SDL2.dll build/win32
	@cp resources/win32/love/license.txt build/win32
	@cp resources/win32/love/lua51.dll build/win32
	@cp resources/win32/love/mpg123.dll build/win32
	@cp resources/win32/love/love.dll build/win32
	@cp resources/win32/love/msvcp120.dll build/win32
	@cp resources/win32/love/msvcr120.dll build/win32

	@cat resources/win32/love/love.exe build/lovefile/clothing-hanger-clicker.love > build/win32/clothing-hanger-clicker.exe

	@mkdir -p build/release
	@rm -f build/release/clothing-hanger-clicker-win32.zip
	@cd build/win32; zip -9 -r ../release/clothing-hanger-clicker-win32.zip .

macos: lovefile
	@rm -rf build/macos
	@mkdir -p "build/macos/Clothing Hanger Clicker.app"

	@cp -r resources/macos/love.app/. "build/macos/Clothing Hanger Clicker.app"

	@cp build/lovefile/clothing-hanger-clicker.love "build/macos/Clothing Hanger Clicker.app/Contents/Resources"

	@mkdir -p build/release
	@rm -f build/release/clothing-hanger-clicker-macos.zip
	@cd build/macos; zip -9 -r ../release/clothing-hanger-clicker-macos.zip .

switch: lovefile
	@rm -rf build/switch
	@mkdir -p build/switch/switch/clothing-hanger-clicker

	@C:/devkitPro/tools/bin/nacptool.exe --create "Clothing Hanger Clicker" GameVasion "0.1.0" build/switch/clothing-hanger-clicker.nacp

	@mkdir build/switch/romfs
	@cp build/lovefile/clothing-hanger-clicker.love build/switch/romfs/game.love

	@C:/devkitPro/tools/bin/elf2nro.exe resources/switch/love.elf build/switch/switch/clothing-hanger-clicker/clothing-hanger-clicker.nro --nacp=build/switch/clothing-hanger-clicker.nacp --romfsdir=build/switch/romfs

	@rm -r build/switch/romfs
	@rm build/switch/clothing-hanger-clicker.nacp

	@mkdir -p build/release
	@rm -f build/release/clothing-hanger-clicker-switch.zip
	@cd build/switch; zip -9 -r ../release/clothing-hanger-clicker-switch.zip .